apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-host
  labels:
    app: echo-host
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-host
        env: production
    spec:
      containers:
      - name: echo-host
        image: schasse/echo-host
        ports:
        - containerPort: 4567
