kind: Service
apiVersion: v1
metadata:
  name: echo-host2
  labels:
    app: echo-host
    env: production
spec:
  type: NodePort
  selector:
    app: echo-host
    env: production
#  clusterIP: 10.0.171.239
  ports:
    - name: http
      protocol: TCP
      port: 80
#      nodePort: 30000
      targetPort: 4567
