apiVersion: v1
kind: Pod
metadata:
  name: superpod
  labels:
    app: superpod
    env: development
spec:
  containers:
  - name: superpod
    image: debian
    lifecycle:
      postStart:
        exec:
          command:
            - bash
            - -c
            - apt-get update && apt-get install -y dnsutils net-tools nmap curl emacs-nox
    command:
      - bash
      - -c
      - while true; do sleep 1; done
  nodeSelector:
    kubernetes.io/hostname: blndindock13
